jobs:
  release:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        java-version: 14
        server-id: central
        server-password: MAVEN_CENTRAL_TOKEN
        server-username: MAVEN_USERNAME
    - continue-on-error: true
      name: Cache Maven packages
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      id: version
      name: Update version
      run: "VERSION=${{ github.event.inputs.version }}\necho \"Updating POMs to version\
        \ $VERSION\"\n./mvnw -B versions:set versions:commit -DnewVersion=$VERSION\n\
        git config --global user.email \"41898282+github-actions[bot]@users.noreply.github.com\"\
        \ngit config --global user.name \"GitHub Action\"\ngit commit -a -m \"\U0001F3C1\
        \ Releasing version $VERSION\"\ngit push origin HEAD:master-11\n"
    - continue-on-error: true
      env:
        MAVEN_CENTRAL_TOKEN: ${{ secrets.SONATYPE_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      name: Release to Maven Central
      run: "export GPG_TTY=$(tty)\n./mvnw --no-transfer-progress -B --file pom.xml\
        \ \\\n  -Drepository.url=https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN\
        \ }}@github.com/${{ github.repository }}.git \\\n  -Dmaven.site.skip=true\
        \ -Drelease=true deploy\n"
    - continue-on-error: true
      env:
        JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Release to GitHub
      run: ./mvnw -B --file pom.xml -Prelease -pl :formsfx jreleaser:full-release
    - continue-on-error: true
      if: always()
      name: JReleaser output
      uses: actions/upload-artifact@v2
      with:
        name: jreleaser-logs
        path: 'target/jreleaser/trace.log

          target/jreleaser/output.properties

          '
name: Release
on:
  repository_dispatch:
    types: trigger-ga___release.yml
